---
- name: Installing and Launch Metricbeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Use command module
  - name: Install metricbeat .deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

    # Use copy module
  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: Enable and Configure System Module
    command: metricbeat modules enable docker

    # Use command module
  - name: Setup metricbeat
    command: metricbeat setup

    # Use command module
  - name: Start metricbeat service
    command: service metricbeat start

    # Use systemd module
  - name: Enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
root@69651336af18:/etc/ansible# cat metricbeat.yml 
output.elasticsearch:
  hosts: ["10.2.0.5"]
  username: "elastic"
  password: "changeme"
setup.kibana:
  host: "10.2.0.5"
metricbeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
root@69651336af18:/etc/ansible# cat metricbeat.yml 
output.elasticsearch:
  hosts: ["10.2.0.5"]
  username: "elastic"
  password: "changeme"
setup.kibana:
  host: "10.2.0.5"
metricbeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
